# Generated by Django 5.1.2 on 2024-11-27 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, editable=False, null=True, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_url', models.URLField(blank=True, max_length=10000, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.author')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        )
    ]
