# Generated by Django 5.1.2 on 2024-11-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
