# Generated by Django 5.1.2 on 2024-10-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='like',
            name='object_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
