# Generated by Django 5.1.2 on 2024-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='plain_or_markdown_content',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post')], default='post', max_length=10),
        ),
        migrations.AlterField(
            model_name='like',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain'), ('text/markdown', 'Markdown'), ('image', 'Image')], default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('FRIENDS', 'Friends'), ('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=10),
        ),
    ]
