# Generated by Django 5.1.2 on 2024-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_content_type_alter_post_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
