# Generated by Django 5.1.2 on 2024-10-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_plain_or_markdown_content_post_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=200, null=True),
        ),
    ]
