# Generated by Django 5.1.2 on 2024-10-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like_content_type_like_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
