# Generated by Django 5.1.2 on 2024-11-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_url',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('FRIENDS', 'Friends'), ('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted'), ('SHARED', 'Shared')], default='PUBLIC', max_length=10),
        ),
    ]
