# Generated by Django 5.1.2 on 2024-11-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_like_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_content',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image'), ('image/gif;base64', 'GIF Image')], default='text/plain', max_length=50),
        ),
    ]
