# Generated by Django 5.1.2 on 2024-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_content_type_alter_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='like',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
