# Generated by Django 5.1.2 on 2024-10-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
