# Generated by Django 5.1.2 on 2024-11-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('remote_node_url', models.URLField(default='https://tavern.com', primary_key=True, serialize=False)),
                ('remote_username', models.CharField(default='TavernToRemote', max_length=100)),
                ('remote_password', models.CharField(default='Tavern-->Remote', max_length=100)),
                ('local_username', models.CharField(default='RemoteToTavern', max_length=100)),
                ('local_password', models.CharField(default='Remote-->Tavern', max_length=100)),
                ('is_whitelisted', models.BooleanField(default=False)),
            ],
        ),
    ]
