# Generated by Django 5.1.2 on 2024-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/c1de2ad1-b66c-4989-b5c5-6365f53798b4', primary_key=True, serialize=False),
        ),
    ]
