# Generated by Django 5.1.2 on 2024-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
