# Generated by Django 5.1.2 on 2024-11-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='host',
        ),
        migrations.RemoveField(
            model_name='node',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='node',
            name='password',
        ),
        migrations.RemoveField(
            model_name='node',
            name='username',
        ),
        migrations.AddField(
            model_name='node',
            name='local_password',
            field=models.CharField(default='Remote-->Tavern', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='local_username',
            field=models.CharField(default='RemoteToTavern', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/24125529-2abd-406a-ab5b-0bd50924d477', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='node',
            name='remote_password',
            field=models.CharField(default='Tavern-->Remote', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='remote_username',
            field=models.CharField(default='TavernToRemote', max_length=100),
        ),
    ]
