# Generated by Django 5.1.2 on 2024-11-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AlterField(
            model_name='node',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
