# Generated by Django 5.1.2 on 2024-11-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/186d1bb4-49a5-4f86-8e16-d2fad1722b13', primary_key=True, serialize=False),
        ),
    ]
