# Generated by Django 5.1.2 on 2024-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/9841aefb-48a8-4f94-afc3-0d1be94aa351', primary_key=True, serialize=False),
        ),
    ]
