# Generated by Django 5.1.2 on 2024-11-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/02da3bdf-aba4-4e3f-8bfd-b3531b7454f2', primary_key=True, serialize=False),
        ),
    ]
