# Generated by Django 5.1.2 on 2024-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/f1109cf0-9fd2-49f3-be13-2bb0c0cb1c36', primary_key=True, serialize=False),
        ),
    ]
