# Generated by Django 5.1.2 on 2024-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/2bb15430-0e6b-461a-a35a-f0b416f828d4', primary_key=True, serialize=False),
        ),
    ]
