# Generated by Django 5.1.2 on 2024-11-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/b3047f1a-e4f3-42cd-b023-29c257b496ee', primary_key=True, serialize=False),
        ),
    ]
