# Generated by Django 5.1.2 on 2024-11-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/ba4b2cf4-821c-4a32-9a70-f2482952317f', primary_key=True, serialize=False),
        ),
    ]
