# Generated by Django 5.1.2 on 2024-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/574bddea-c356-4ea2-85e1-032295201a17', primary_key=True, serialize=False),
        ),
    ]
