# Generated by Django 5.1.2 on 2024-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/1b6a1072-deca-4d4e-99bb-663ec8cc7d50', primary_key=True, serialize=False),
        ),
    ]
