# Generated by Django 5.1.2 on 2024-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/2a547aba-f0b3-4cf5-aab3-63f3cf696b84', primary_key=True, serialize=False),
        ),
    ]
