# Generated by Django 5.1.2 on 2024-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/0e1c29f4-be60-4616-a403-0e722acb9597', primary_key=True, serialize=False),
        ),
    ]
