# Generated by Django 5.1.2 on 2024-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/0313adff-4dca-4f65-8a97-41438d32018d', primary_key=True, serialize=False),
        ),
    ]
