# Generated by Django 5.1.2 on 2024-11-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/45cd92c8-8365-444f-b9b8-1608573c3404', primary_key=True, serialize=False),
        ),
    ]
