# Generated by Django 5.1.2 on 2024-11-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/0dff07d4-e4ca-4c1b-99b2-f462a3618766', primary_key=True, serialize=False),
        ),
    ]
