# Generated by Django 5.1.2 on 2024-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/3ab306f4-5160-40e4-bffa-9909691efb42', primary_key=True, serialize=False),
        ),
    ]
