# Generated by Django 5.1.2 on 2024-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/46356759-3443-4984-b3ab-bcf88b5b7c03', primary_key=True, serialize=False),
        ),
    ]
