# Generated by Django 5.1.2 on 2024-11-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/cf441481-01a3-4421-830e-3e59449a6234', primary_key=True, serialize=False),
        ),
    ]
