# Generated by Django 5.1.2 on 2024-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/65f9bbec-ab92-4e98-8a03-8968fb50d4bb', primary_key=True, serialize=False),
        ),
    ]
