# Generated by Django 5.1.2 on 2024-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/62a37cc2-42e9-4348-bada-fcd201815d78', primary_key=True, serialize=False),
        ),
    ]
