# Generated by Django 5.1.2 on 2024-11-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/f7b9d096-3dc3-4122-81bc-00474d7245b9', primary_key=True, serialize=False),
        ),
    ]
