# Generated by Django 5.1.2 on 2024-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/de2e749c-b530-43f6-8bad-9b600ad3573e', primary_key=True, serialize=False),
        ),
    ]
