# Generated by Django 5.1.2 on 2024-11-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/8a992a89-c448-4e50-9189-e57f4827dbfd', primary_key=True, serialize=False),
        ),
    ]
