# Generated by Django 5.1.2 on 2024-11-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/94fa1626-9923-456c-b768-af9a38fdc606', primary_key=True, serialize=False),
        ),
    ]
