# Generated by Django 5.1.2 on 2024-11-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/4dfe4d73-7fc8-4212-a240-b47497baa93a', primary_key=True, serialize=False),
        ),
    ]
