# Generated by Django 5.1.2 on 2024-11-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/59c47d65-dd48-43f9-a7ba-a48a9d22455f', primary_key=True, serialize=False),
        ),
    ]
