# Generated by Django 5.1.2 on 2024-11-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0012_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/a95ee200-5aef-4a22-a4f6-a4d6cbee2d5a', primary_key=True, serialize=False),
        ),
    ]
