# Generated by Django 5.1.2 on 2024-11-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0013_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/04cce923-b57b-45df-a6aa-56206cae2fd2', primary_key=True, serialize=False),
        ),
    ]
