# Generated by Django 5.1.2 on 2024-11-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0014_alter_node_remote_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='remote_node_url',
            field=models.URLField(default='http://example.com/node/2eb1d0b5-bbb7-4008-bfe0-deae71d71cc6', primary_key=True, serialize=False),
        ),
    ]
