# Generated by Django 5.1.2 on 2024-11-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
