# Generated by Django 5.1.2 on 2024-10-16 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_follower_url', models.URLField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Follow Request Pending'), ('ACCEPTED', 'Follow Request Accepted')], max_length=50)),
                ('followed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.author')),
                ('local_follower_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.author')),
            ],
        ),
    ]
