# Generated by Django 5.1.2 on 2024-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_author_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
